### ISSUE TITLE
zpětná vazba - 2. DÚ vizitka

### ISSUE THREAD

**Issue by LukasHypsa** [evavalentova/PROJEKT-Vizitka#1]
Ahoj, 
úkol je skvěle zpracovaný, všechny vzdálenosti sedí, dohledala sis i vlastnosti na stínování a na zvětšení písma, skvělá práce :) 
Našel jsem tam jen 2 drobnosti:¨

1, při najetí na tlačítka přestanou být rohy oblé. Co se děje?
Jde o to, že oblé rohy jsi nastavila pouze třídám .facebook a .twitter, které jsou "pod odkazy". Ovšem ten odkaz, který leží "přes" má hranaté rohy pořád :) Jen má v základu průhledné pozadí, takže to není vidět. Při najetí na odkaz se ale změní pozadí na nějakou barvu a uživatel tak najednou před sebou vidí odkaz, který rohy zaoblené nemá. 
To je první věc, kterou bych tě poprosil, abys opravila :) 

2, Třídy  .facebook a .twitter mají 5 vlastností stejných a jen 2 různé. Chtěl bych, abys těch 5 vlastností spojila jen do jednoho zápisu :) pro jistotu připomenu, že funguje například toto:
.fb, .ig {
color: red;
}
V předchozím příkladu jsem před závorky {} napsal 2 třídy oddělené čárkou, vlastnosti v závorkách se tak aplikují na obě třídy. Možných řešení je ale víc :)

Jakmile 2 drobnosti upravíš, pushni je prosím na GIT a napiš mi (třeba tady) info žes tak udělala.
Jinak myslím, že úkol jsi udělala moc dobře a za mě jsi ho určitě splnila :)
Lukáš

**Comment by LukasHypsa** [comment]
PS: Kdyby ses na cokoliv chtěla doptat, klidně se ozvi na slacku, nebo se o tom můžem pobavit na středeční konzultaci :)

**Comment by evamarko** [comment]
Ahoj, děkuji moc za feedback! Upravila jsem a pushla na GIT. Dej vědět, jestli je to ok. :-) 

Jinak ohledně té hromadné deklarace: H1, H2, H3 {color: red} , jaké jsou ještě další možnosti, které se využívají?

Eva

**Comment by LukasHypsa** [comment]
Ahoj, díky za opravy :) ted je to v pohodě.
Další možnost by byla třeba taková, že bys přidala tlačítkům další společnou třídu, kterou by měly obě a tý bys pak dala společné atributy :) 
Ve středu se klidně doptej.
